laserscan_multi_merger:
  ros__parameters:
    destination_frame: "base_link"
    cloud_destination_topic: "/merged_cloud"
    scan_destination_topic: "/scan"
    laserscan_topics: "/right_scan /left_scan"
    angle_min: -3.1415
    angle_max: 3.1415
    angle_increment: 0.001
    scan_time: 0.0
    range_min: 0.05
    range_max: 25.0

